<?php
return array (
  'permission_interface.aiconnect_general' => 'AI Connect',
  'permission_interface.aiconnect_pkg_activity_analytics' => 'AI Connect Pro — Activity & Analytics',
  'permission_interface.aiconnect_pkg_admin' => 'AI Connect Admin — Board Administration',
  'permission_interface.aiconnect_pkg_advanced_mod' => 'AI Connect Pro — Advanced Mod (merge/split)',
  'permission_interface.aiconnect_pkg_approval' => 'AI Connect Pro — Approval Queue',
  'permission_interface.aiconnect_pkg_automation' => 'AI Connect Pro — Automation',
  'permission_interface.aiconnect_pkg_conversation' => 'AI Connect Pro — Conversation',
  'permission_interface.aiconnect_pkg_core' => 'AI Connect Pro — Core',
  'permission_interface.aiconnect_pkg_discovery' => 'AI Connect Pro — Discovery',
  'permission_interface.aiconnect_pkg_engagement' => 'AI Connect Pro — Engagement',
  'permission_interface.aiconnect_pkg_forum_watch' => 'AI Connect Pro — Forum Watch (watch/unwatch)',
  'permission_interface.aiconnect_pkg_media' => 'AI Connect Pro — Media',
  'permission_interface.aiconnect_pkg_moderation' => 'AI Connect Pro — Moderation',
  'permission_interface.aiconnect_pkg_notifications' => 'AI Connect Pro — Notifications & Alerts',
  'permission_interface.aiconnect_pkg_profile' => 'AI Connect Pro — Profile',
  'permission_interface.aiconnect_pkg_reports' => 'AI Connect Pro — Reports Queue',
  'permission_interface.aiconnect_pkg_thread_content' => 'AI Connect Pro — Thread Content (posts/polls)',
  'permission_interface.aiconnect_pkg_user_content' => 'AI Connect Pro — User Content (bookmarks/DMs)',
  'permission_interface.aiconnect_pkg_users_groups' => 'AI Connect Pro — Users & Groups',
  'permission_interface.aiconnect_pkg_warnings' => 'AI Connect Pro — Warnings (issue/list/delete)',
  'permission_interface.aiconnect_pkg_watched_bookmarks' => 'AI Connect Pro — Watched & Bookmarks',
  'permission_interface.aiconnect_pkg_writing' => 'AI Connect Pro — Writing',
  'permission_interface.aiconnect_tools' => 'AI Connect — Tools',
  'permission_interface.bookmarkPermissions' => 'Bookmark permissions',
  'permission_interface.conversationModeratorPermissions' => 'Direct message moderator permissions',
  'permission_interface.conversationPermissions' => 'Direct message permissions',
  'permission_interface.forumModeratorPermissions' => 'Forum moderator permissions',
  'permission_interface.forumPermissions' => 'Forum permissions',
  'permission_interface.generalModeratorPermissions' => 'General moderator permissions',
  'permission_interface.generalPermissions' => 'General permissions',
  'permission_interface.postAttachmentPermissions' => 'Post attachment permissions',
  'permission_interface.profilePostModeratorPermissions' => 'Profile post moderator permissions',
  'permission_interface.profilePostPermissions' => 'Profile post permissions',
  'permission_interface.signaturePermissions' => 'Signature permissions',
);